name: Publish docker image

on:
  push:
    branches:
      - master

jobs:

  build:
    name : build master branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.X'

      - name: Maven Build
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        run: docker build -t test-registry .

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: gjambet/chuck-facts/chuck-facts
          tag_with_ref: true