name: Publish docker image

on:
  push:
    branches:
      - master

jobs:

  build:
    name : build master branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
      
      - name: Maven Build & Sonar analysis
#        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        run: mvn -B verify --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Build Docker image
        run: docker build . --tag ghcr.io/gjambet/chuck-facts:latest

      - name: Publish Docker image
        run: docker push ghcr.io/gjambet/chuck-facts:latest
        
